apiVersion: v1
kind: Service
metadata:
  name: blue-green-node-dev
  labels:
    app: blue-green-node
    isProduction: "false"
spec:
  ports:
  - name: blue-green-node
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: blue-green-node
    version: {IMAGE_TAG_OLD}
  type: LoadBalancer
